FantasyHockeySite/FantasyHockeySite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView
from fantasy import views


urlpatterns = [
    path('', views.index, name='index'),
    path('home', views.index, name='home'),
    path('fantasy/', include('fantasy.urls', namespace='fantasy')),
    path('admin/', admin.site.urls),
    re_path('api/(?P<version>(v1|v2))/', include('apis.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

FantasyHockeySite/apis/urls.py
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 30 14:06:04 2019

@author: Eiden
"""

from django.urls import path
from apis import views
#from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('leagues/', views.ListAllLeaguesView.as_view(), name="leagues-all"),
    path('leagues/<str:pk>/', views.ListTeamsInLeagueView.as_view(), name="teams-by-league"),
    path('teams/', views.ListAllTeamsView.as_view(), name="teams-all"),
    path('teams/<int:pk>/', views.ListAllTeamPlayersView.as_view(), name="players-by-fantasy-team"),
    path('nhlteams/', views.ListAllNhlTeamsView.as_view(), name="nhlteams-all"),
    path('nhlteams/<str:pk>/', views.ListPlayersInNhlTeamView.as_view(), name="nhlplayer-by-nhlteam")
]
#urlpatterns = format_suffix_patterns(urlpatterns)

FantasyHockeySite/fantasy/urls.py
from django.urls import path

from . import views


app_name = 'fantasy'

urlpatterns = [
    path('', views.index, name='index'),
    path('nhl_players/', views.nhl_players, name='nhl_players'),
    path('nhl_teams/', views.nhl_teams, name='nhl_teams'),
    path('search_nhl_player/', views.search_nhl_player, name='search_nhl_player'),
    path('search_player/', views.search_player, name='search_player'),
    path('create_fantasy_league/', views.create_fantasy_league, name='create_fantasy_league'),
    path('create_league/', views.create_league, name='create_league'),
    path('edit_fantasy_league_rules/', views.edit_fantasy_league_rules, name='edit_fantasy_league_rules'),
    path('edit_fantasy_league_rules/<str:league_name>', views.edit_league_rules, name='edit_league_rules'),
    path('edit_fantasy_league_rules/<str:league_name>/update_rules', views.update_rules, name='update_rules'),
    path('view_fantasy_league_invite_code/', views.view_fantasy_league_invite_code, name='view_fantasy_league_invite_code'),
    path('join_fantasy_league/', views.join_fantasy_league, name='join_fantasy_league'),
    path('join_league/', views.join_league, name='join_league'),
    path('create_fantasy_team/', views.create_fantasy_team_show_leagues, name='create_fantasy_team_show_leagues'),
    path('create_fantasy_team/<str:league_name>/', views.create_fantasy_team, name='create_fantasy_team'),
    path('create_fantasy_team/<str:league_name>/create_team/', views.create_team, name='create_team'),
    path('edit_fantasy_teams/', views.edit_fantasy_teams, name='edit_fantasy_teams'),
    path('edit_fantasy_teams/<int:team_id>/', views.select_action, name='select_action'),
    path('edit_fantasy_teams/<int:team_id>/add_goalie/', views.add_goalie, name='add_goalie'),
    path('edit_fantasy_teams/<int:team_id>/add_center/', views.add_center, name='add_center'),
    path('edit_fantasy_teams/<int:team_id>/add_left_wing/', views.add_left_wing, name='add_left_wing'),
    path('edit_fantasy_teams/<int:team_id>/add_right_wing/', views.add_right_wing, name='add_right_wing'),
    path('edit_fantasy_teams/<int:team_id>/add_defencemen/', views.add_defencemen, name='add_defencemen'),
    path('edit_fantasy_teams/<int:team_id>/add_player/<int:nhl_id>/', views.add, name='add'),
    path('edit_fantasy_teams/<int:team_id>/remove_goalie/', views.remove_goalie, name='remove_goalie'),
    path('edit_fantasy_teams/<int:team_id>/remove_center/', views.remove_center, name='remove_center'),
    path('edit_fantasy_teams/<int:team_id>/remove_left_wing/', views.remove_left_wing, name='remove_left_wing'),
    path('edit_fantasy_teams/<int:team_id>/remove_right_wing/', views.remove_right_wing, name='remove_right_wing'),
    path('edit_fantasy_teams/<int:team_id>/remove_defencemen/', views.remove_defencemen, name='remove_defencemen'),
    path('edit_fantasy_teams/<int:team_id>/remove_player/<int:nhl_id>/', views.remove, name='remove'),
    path('view_fantasy_teams/', views.view_fantasy_teams, name='view_fantasy_teams'),
    path('view_fantasy_teams/<int:teamid>/', views.view_fantasy_team_players, name='view_fantasy_team_players'),
    path('view_fantasy_leagues/', views.view_fantasy_leagues, name='view_fantasy_leagues'),
    path('view_fantasy_leagues/<str:f_name>', views.view_fantasy_league_teams, name='view_fantasy_league_teams'),
]

FantasyHockeySite/fantasy/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

FantasyHockeySite/fantasy/views.py
import decimal

from django.shortcuts import render
from django.db import connection
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError

from .models import NhlPlayers, NhlTeam, NhlSkaters, NhlGoalies, FantasyLeague, LeagueCommissioner, Participates, FantasyTeam, GoalieTeams, SkaterTeams


# Create your views here.
def index(request):
    return render(request, 'fantasy/index.html')


def nhl_players(request):
    skaters = NhlSkaters.objects.select_related('id').all().order_by('id__team_name', 'id__name')
    goalies = NhlGoalies.objects.select_related('id').all().order_by('id__team_name', 'id__name')
    return render(request, 'fantasy/display_players.html', {'skaters': skaters, 'goalies': goalies})


def nhl_teams(request):
    query_results = NhlTeam.objects.all()
    return render(request, 'fantasy/nhl_team.html', {'query_results': query_results})


def search_nhl_player(request):
    return render(request, 'fantasy/search_nhl_player.html')


def search_player(request):
    tn = request.GET.get('team_name').strip()
    jn = request.GET.get('jersey_number').strip()
    n = request.GET.get('name').strip()
    if tn == '' and jn == '' and n == '':
        return render(request, 'fantasy/display_message.html', {'message': 'No parameters entered, search was not performed'})
    teams = NhlTeam.objects.filter(team_name__icontains=tn)
    if jn == '':
        skaters = NhlSkaters.objects.select_related('id').filter(id__team_name__in=teams, id__name__icontains=n)
        goalies = NhlGoalies.objects.select_related('id').filter(id__team_name__in=teams, id__name__icontains=n)
    else:
        skaters = NhlSkaters.objects.select_related('id').filter(id__team_name__in=teams, id__jersey_number=jn, id__name__icontains=n)
        goalies = NhlGoalies.objects.select_related('id').filter(id__team_name__in=teams, id__jersey_number=jn, id__name__icontains=n)
    return render(request, 'fantasy/display_players.html', {'skaters': skaters, 'goalies': goalies})


def create_fantasy_league(request):
    return render(request, 'fantasy/create_fantasy_league.html')


def create_league(request):
    n = request.POST['name'].strip()
    c = request.POST['code']
    # check for unique name and code
    if FantasyLeague.objects.filter(fantasy_league_name=n).exists():
        return render(request, 'fantasy/display_message.html', {'message': 'League name \"' + n + '\" already exists'})
    elif FantasyLeague.objects.filter(fantasy_league_invite_code=c):
        return render(request, 'fantasy/display_message.html', {'message': 'Invite code \"' + c + '\" already exists'})
    elif n == '' or c == '':
        return render(request, 'fantasy/display_message.html', {'message': 'Please enter a name and an invite code'})
    else:
        u_id = request.user.id
        u_id = get_object_or_404(get_user_model(), pk=u_id)
        if not LeagueCommissioner.objects.filter(userid=u_id).exists():
            commissioner = LeagueCommissioner.objects.create(userid=u_id)
        else:
            commissioner = get_object_or_404(LeagueCommissioner, pk=u_id)

        league = FantasyLeague.objects.create(fantasy_league_name=n, fantasy_league_invite_code=c, commissionerid=commissioner)
        return render(request, 'fantasy/display_message.html', {'message': 'Fantasy league \"' + n + '\" was sucessfully created, please edit the rules before inviting people to join the league'})


def view_fantasy_league_invite_code(request):
    u_id = request.user.id
    if not LeagueCommissioner.objects.filter(userid=u_id).exists():
        return render(request, 'fantasy/display_message.html', {'message': 'You are currently not a league commisioner'})
    else:
        commissioner = get_object_or_404(LeagueCommissioner, pk=u_id)
        leagues = FantasyLeague.objects.filter(commissionerid=commissioner)
        return render(request, 'fantasy/view_fantasy_league_invite_code.html', {'query_results': leagues})


def join_fantasy_league(request):
    return render(request, 'fantasy/join_fantasy_league.html')


def join_league(request):
    c = request.POST['code']
    # check for valid code
    if not FantasyLeague.objects.filter(fantasy_league_invite_code=c).exists():
        return render(request, 'fantasy/display_message.html', {'message': 'Fantasy league with invite code \"' + c + '\" does not exist'})

    # check if user is already participating in the league
    u_id = request.user.id
    u_id = get_object_or_404(get_user_model(), pk=u_id)
    league = get_object_or_404(FantasyLeague, fantasy_league_invite_code=c)
    if Participates.objects.filter(userid=u_id).filter(fantasy_league_name=league).exists():
        return render(request, 'fantasy/display_message.html', {'message': 'You are already participating in this fantasy league'})

    p = Participates.objects.create(userid=u_id, fantasy_league_name=league)
    return render(request, 'fantasy/display_message.html', {'message': 'Sucessfully joined fantasy league \"' + league.fantasy_league_name + '\"'})


def create_fantasy_team_show_leagues(request):
    u_id = request.user.id
    u_id = get_object_or_404(get_user_model(), pk=u_id)
    # get fantasy leagues where the user doesn't have a fantasy team
    teams = FantasyTeam.objects.filter(userid=u_id).values_list('fantasy_league_name', flat=True)
    leagues = Participates.objects.filter(userid=u_id).exclude(fantasy_league_name__in=teams)

    if not leagues.exists():
        return render(request, 'fantasy/display_message.html', {'message': 'You have no available teams to create'})
    else:
        return render(request, 'fantasy/create_fantasy_team_show_leagues.html', {'query_results': leagues})


def create_fantasy_team(request, league_name):
    league = get_object_or_404(FantasyLeague, pk=league_name)
    return render(request, 'fantasy/create_fantasy_team.html', {'league': league})


def create_team(request, league_name):
    n = request.POST['name']
    if not FantasyTeam.objects.filter(fantasy_team_name=n, fantasy_league_name=league_name).exists():
        # create the fantasy team
        u_id = request.user.id
        u_id = get_object_or_404(get_user_model(), pk=u_id)
        league = get_object_or_404(FantasyLeague, fantasy_league_name=league_name)
        ft = FantasyTeam.objects.create(fantasy_team_name=n, fantasy_league_name=league, userid=u_id)

        # populate with randomly selected goalies
        min_goalies = league.minimum_number_of_goalies
        temp = NhlGoalies.objects.order_by('?')[:min_goalies]
        for item in temp:
            GoalieTeams.objects.create(playerid=item.id, team_id=ft)

        # populate with randomly selected defencemen
        min_def = league.minimum_number_of_defencemen
        temp = NhlSkaters.objects.filter(defencemen_flag=1).order_by('?')[:min_def]
        for item in temp:
            SkaterTeams.objects.create(playerid=item.id, team_id=ft)

        # populate with randomly selected right wing
        min_right = league.minimum_number_of_right_wing
        temp = NhlSkaters.objects.filter(right_wing_flag=1).order_by('?')[:min_right]
        for item in temp:
            SkaterTeams.objects.create(playerid=item.id, team_id=ft)

        # populate with randomly selected left wing
        min_left = league.minimum_number_of_left_wing
        temp = NhlSkaters.objects.filter(left_wing_flag=1).order_by('?')[:min_left]
        for item in temp:
            SkaterTeams.objects.create(playerid=item.id, team_id=ft)

        # populate with randomly selected center
        min_cen = league.minimum_number_of_center
        temp = NhlSkaters.objects.filter(center_flag=1).order_by('?')[:min_cen]
        for item in temp:
            SkaterTeams.objects.create(playerid=item.id, team_id=ft)

        return render(request, 'fantasy/display_message.html', {'message': 'Sucessfully created fantasy team \"' + n  + '\" with randomly selected players'})
    else:
        return render(request, 'fantasy/display_message.html', {'message': 'Team name \"' + n  + '\" already exists within the league, team was not created'})


def edit_fantasy_teams(request):
    u_id = request.user.id
    u_id = get_object_or_404(get_user_model(), pk=u_id)
    teams = FantasyTeam.objects.filter(userid=u_id)
    return render(request, 'fantasy/edit_fantasy_teams.html', {'teams': teams})


def select_action(request, team_id):
    team = get_object_or_404(FantasyTeam, pk=team_id)
    val = validate_user(request, team)
    if not val[0]:
        return render(request, 'fantasy/display_message.html', {'message': val[1]})
    return render(request, 'fantasy/select_action.html', {'team': team})


def add_goalie(request, team_id):
    team = get_object_or_404(FantasyTeam, pk=team_id)
    val = validate_user(request, team)
    if not val[0]:
        return render(request, 'fantasy/display_message.html', {'message': val[1]})
    max_players = team.fantasy_league_name.maximum_number_of_players
    count = SkaterTeams.objects.filter(team_id=team.id).count()
    count += GoalieTeams.objects.filter(team_id=team.id).count()
    if max_players <= count:
        return render(request, 'fantasy/display_message.html', {'message': 'You have reached the maximum ('+ str(max_players) +') allowable number of players for this league'})
    current_goalies = GoalieTeams.objects.filter(team_id=team).values_list('playerid', flat=True)
    available_goalies = NhlGoalies.objects.all().exclude(id__in=current_goalies)
    order_by = request.GET.get('order_by', 'defaultOrderField')
    if order_by=='team_name' or order_by=='defaultOrderField':
        available_goalies = available_goalies.order_by('id__team_name', 'id__name')
    elif order_by=='name':
        available_goalies = available_goalies.order_by('id__name', 'id__team_name')
    return render(request, 'fantasy/add_goalie.html', {'team': team, 'available_goalies': available_goalies})

FantasyHockeySite/fantasy/templates/fantasy/add_goalie.html
{% extends 'fantasy/base.html' %}

{% block content %}
    <h3>Add Goalie</h3>
    <br>
	<a href="{% url 'fantasy:select_action' team.id %}"><button type="button" class="btn btn-secondary">Return to Team Edit</button></a>
	<br><br>
    <table class="table">
        <tr>
			<th> </th>
            <th>Jersey Number</th>
            <th><a href="?order_by=team_name">Team Name</a></th>
            <th><a href="?order_by=name">Name</a></th>
            <th>Games Played</th>
            <th>Wins</th>
            <th>Losses</th>
            <th>Overtime Lossses</th>
            <th>Shots Against</th>
            <th>Saves</th>
            <th>Shutouts</th>
        </tr>
        {% for item in available_goalies %}
        <tr>
            <td><a href="{% url 'fantasy:add' team.id item.id.id %}">  Add player  </a></td>
            <td>{{ item.id.jersey_number }}</td>
            <td>{{ item.id.team_name.team_name }}</td>
            <td>{{ item.id.name }}</td>
            <td>{{ item.id.games_played }}</td>
            <td>{{ item.wins }}</td>
            <td>{{ item.losses }}</td>
            <td>{{ item.overtime_losses }}</td>
            <td>{{ item.shots_against }}</td>
            <td>{{ item.saves }}</td>
            <td>{{ item.shutouts }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

FantasyHockeySite/fantasy/templates/fantasy/base.html
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% if user.is_authenticated %}
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
            <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'fantasy:index' %}">Fantasy Hockey Project</a></h5>
            <nav class="my-2 my-md-0 mr-md-3">
              <a class="p-2 text-dark" href="{% url 'fantasy:index' %}">Home</a>
              <a class="p-2 text-dark" href="{% url 'logout' %}">Logout</a>
            </nav>
        </div>
        <div class="row">
				<div class="col-1"></div>
				<div class="col-10">
						{% block content %}
						{% endblock %}
				</div>
				<div class="col-1"></div>
        </div>
        {% else %}
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
            <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'fantasy:index' %}">Fantasy Hockey Project</a></h5>
        </div>
        <div class="row">
				<div class="col-1"></div>
				<div class="col-10">
                    <p><h4>Welcome to the Fantasy Hockey Project</h4></p>
                    <a href="{% url 'login' %}"><button type="button" class="btn btn-primary">Log In</button></a>
                    <a href="{% url 'signup' %}"><button type="button" class="btn btn-secondary">Sign Up</button></a>
				</div>
				<div class="col-1"></div>
        </div>
        
    {% endif %}

</body>

</html>

FantasyHockeySite/fantasy/templates/fantasy/create_fantasy_league.html
{% extends 'fantasy/base.html' %}

{% block content %}
    <h3>Create Fantasy League</h3>
    <br>
    <form action="{% url 'fantasy:create_league' %}" method="post">
        {% csrf_token %}
        Fantasy League Name:<br> <input type="text" name="name">
        <br>
        Invite Code:<br> <input type="text" name="code">
        <br><br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

FantasyHockeySite/fantasy/templates/fantasy/create_fantasy_team.html
{% extends 'fantasy/base.html' %}

{% block content %}
    <h3>Create Fantasy Team</h3>
    <br>
    <form action="{% url 'fantasy:create_team' league.fantasy_league_name %}" method="post">
        {% csrf_token %}
        Team Name:<br> <input type="text" name="name">
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

FantasyHockeySite/fantasy/templates/fantasy/create_fantasy_team_show_leagues.html
{% extends 'fantasy/base.html' %}

{% block content %}
    <h3>Create Fantasy Team</h3>
    <br>
    <table class="table">
        <tr>
            <th>League Name</th>
        </tr>
        {% for item in query_results %}
        <tr>
            <td> <a href="{% url 'fantasy:create_fantasy_team' item.fantasy_league_name.fantasy_league_name %}">{{ item.fantasy_league_name.fantasy_league_name }}</a> </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

FantasyHockeySite/fantasy/templates/fantasy/display_message.html
{% extends 'fantasy/base.html' %}

{% block content %}
    <h3>Message</h3>
    <br>
    {{ message }}
    {% if returnToTeamEdit %}
        <br>
        <br>
        <a href="{% url 'fantasy:select_action' team_id %}"><button type="button" class="btn btn-secondary">Return to Team Edit</button></a>
    {% endif %}
{% endblock %}

FantasyHockeySite/fantasy/templates/fantasy/edit_fantasy_league_rules.html
{% extends 'fantasy/base.html' %}

{% block content %}
    <h3>Edit League Rules</h3>
    <br>
    <table class="table">
        <tr>
            <th>League Name</th>
        </tr>
        {% for item in leagues %}
        <tr>
            <td><a href="{% url 'fantasy:edit_league_rules' item.fantasy_league_name %}">{{ item.fantasy_league_name }}</a></td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

FantasyHockeySite/fantasy/templates/fantasy/index.html
{% extends 'fantasy/base.html' %}

{% block content %}
    {% csrf_token %}
    <h3>Homepage</h3>
    <br>
    <div class="list-group">
      <a href="{% url 'fantasy:nhl_players' %}" class="list-group-item list-group-item-action">NHL Players</a>
      <a href="{% url 'fantasy:nhl_teams' %}" class="list-group-item list-group-item-action">NHL Teams</a>
      <a href="{% url 'fantasy:search_nhl_player' %}" class="list-group-item list-group-item-action">Search NHL Player</a>
      <a href="{% url 'fantasy:create_fantasy_league' %}" class="list-group-item list-group-item-action">Create Fantasy League</a>
      <a href="{% url 'fantasy:edit_fantasy_league_rules' %}" class="list-group-item list-group-item-action">Edit Fantasy League Rules</a>
      <a href="{% url 'fantasy:view_fantasy_league_invite_code' %}" class="list-group-item list-group-item-action">View Fantasy League Invite Code</a>
      <a href="{% url 'fantasy:join_fantasy_league' %}" class="list-group-item list-group-item-action">Join Fantasy League</a>
      <a href="{% url 'fantasy:create_fantasy_team_show_leagues' %}" class="list-group-item list-group-item-action">Create Fantasy Team</a>
      <a href="{% url 'fantasy:edit_fantasy_teams' %}" class="list-group-item list-group-item-action">Edit Fantasy Teams</a>
      <a href="{% url 'fantasy:view_fantasy_teams' %}" class="list-group-item list-group-item-action">View Fantasy Teams</a>
      <a href="{% url 'fantasy:view_fantasy_leagues' %}" class="list-group-item list-group-item-action">View Fantasy Leagues</a>
    </div>
{% endblock %}

FantasyHockeySite/fantasy/templates/fantasy/remove_skater.html
{% extends 'fantasy/base.html' %}

{% block content %}
    <h3>Remove Skater</h3>
    <br>
    <a href="{% url 'fantasy:select_action' team.id %}"><button type="button" class="btn btn-secondary">Return to Team Edit</button></a>
    <table class="table">
        <tr>
            <th>  </th>
            <th>Jersey Number</th>
            <th>Team Name</th>
            <th>Name</th>
            <th>Games Played</th>
            <th>Goals</th>
            <th>Powerplay Goals</th>
            <th>Powerplay Points</th>
            <th>Shorthanded Goals</th>
            <th>Shorthanded Points</th>
            <th>+/-</th>
            <th>Penalty Minutes</th>
            <th>Game Winning Goals</th>
            <th>Shots on Goal</th>
            <th>Position</th>
        </tr>
        {% for item in skaters %}
        <tr>
            <td><a href="{% url 'fantasy:remove' team.id item.id.id %}">Remove player</a></td>
            <td>{{ item.id.jersey_number }}</td>
            <td>{{ item.id.team_name.team_name }}</td>
            <td>{{ item.id.name }}</td>
            <td>{{ item.id.games_played }}</td>
            <td>{{ item.goals }}</td>
            <td>{{ item.powerplay_goals }}</td>
            <td>{{ item.powerplay_points }}</td>
            <td>{{ item.shorthanded_goals }}</td>
            <td>{{ item.shorthanded_points }}</td>
            <td>{{ item.plus_minus }}</td>
            <td>{{ item.penalty_minutes }}</td>
            <td>{{ item.game_winning_goals }}</td>
            <td>{{ item.shots_on_goal }}</td>
            {% if item.center_flag == 1 %}
            <td>{{ "Center" }}</td>
            {% endif %}
            {% if item.left_wing_flag == 1 %}
            <td>{{ "Left Wing" }}</td>
            {% endif %}
            {% if item.right_wing_flag == 1 %}
            <td>{{ "Right Wing" }}</td>
            {% endif %}
            {% if item.defencemen_flag == 1 %}
            <td>{{ "Defencemen" }}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
{% endblock %}

FantasyHockeySite/fantasy/templates/fantasy/select_action.html
{% extends 'fantasy/base.html' %}

{% block content %}
  <h3>Edit Team</h3>
  <br>
  <div class="list-group">
    <a href="{% url 'fantasy:add_goalie' team.id %}" class="list-group-item list-group-item-action">Add Goalie</a>
    <a href="{% url 'fantasy:remove_goalie' team.id %}" class="list-group-item list-group-item-action">Remove Goalie</a>
    <a href="{% url 'fantasy:add_center' team.id %}" class="list-group-item list-group-item-action">Add Center</a>
    <a href="{% url 'fantasy:remove_center' team.id %}" class="list-group-item list-group-item-action">Remove Center</a>
    <a href="{% url 'fantasy:add_left_wing' team.id %}" class="list-group-item list-group-item-action">Add Left Wing</a>
    <a href="{% url 'fantasy:remove_left_wing' team.id %}" class="list-group-item list-group-item-action">Remove Left Wing</a>
    <a href="{% url 'fantasy:add_right_wing' team.id %}" class="list-group-item list-group-item-action">Add Right Wing</a>
    <a href="{% url 'fantasy:remove_right_wing' team.id %}" class="list-group-item list-group-item-action">Remove Right Wing</a>
    <a href="{% url 'fantasy:add_defencemen' team.id %}" class="list-group-item list-group-item-action">Add Defencemen</a>
    <a href="{% url 'fantasy:remove_defencemen' team.id %}" class="list-group-item list-group-item-action">Remove Defencemen</a>
    <a href="{% url 'fantasy:view_fantasy_team_players' team.id %}" class="list-group-item list-group-item-action">View Current Team</a>
  </div>
{% endblock %}

FantasyHockeySite/fantasy/templates/fantasy/view_fantasy_league_invite_code.html
{% extends 'fantasy/base.html' %}

{% block content %}
    <h3>View Invite Codes</h3>
    <br>
    <table class="table">
        <tr>
            <th>League Name</th>
            <th>Invite Code</th>
        </tr>
        {% for item in query_results %}
        <tr>
            <td>{{ item.fantasy_league_name }}</td>
            <td>{{ item.fantasy_league_invite_code }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}